title: My first Github Page
author: Katarina
email: whatever@whatever.com
description: > # this means to ignore newlines until "baseurl:"
  Some description because why not

# social links
github_username:  Katarina799

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
